name: pyright-action

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v6
      with:
          cache: 'pip'
    - uses: jakebailey/pyright-action@v3
